### ISSUE TITLE
After change AndroidManifest can not build

### ISSUE THREAD

**Issue by ddt626** [yatharth25/android_dynamic_icon#1]
after I comment 
![image](https://github.com/yatharth25/android_dynamic_icon/assets/4536733/2ff1100d-f421-4a3b-a168-1fce92ff9c78)

I got this error

`package identifier or launch activity not found.
Please check dynamic_icon/android/app/src/main/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.
`

Could you help to fix this issue?

**Comment by Joel134** [comment]
Hey, You won't be able to run code with commenting this. I think the repo owner should consider changing this in readme file.
[https://github.com/flutter/flutter/issues/28122#issue-411684870](url)

**Comment by yatharth25** [comment]
> after I comment ![image](https://user-images.githubusercontent.com/4536733/243654975-2ff1100d-f421-4a3b-a168-1fce92ff9c78.png)
> 
> I got this error
> 
> `package identifier or launch activity not found. Please check dynamic_icon/android/app/src/main/AndroidManifest.xml for errors. No application found for TargetPlatform.android_arm64. Is your project missing an android/app/src/main/AndroidManifest.xml? Consider running "flutter create ." to create one. `
> 
> Could you help to fix this issue?

Hi @ddt626 
I have noticed this issue and working on it. but meanwhile, you can try the below solution which can help you fix this.

Please try uncommenting "main action" intent filter and run the app,
App cannot be built without main action intent. so you have to first run with main action intent uncommented.
as soon as you get debug apk built as you run it.  Now you can comment the main intent and it should work as expected forever.

**Comment by yatharth25** [comment]
@ddt626 @Joel134 Please refer to latest version 2.0.0 as the implementation is changed completely now, and all the issues ate fixed.
