### ISSUE TITLE
Dynamic Changing Icon Issue in Android

### ISSUE THREAD

**Issue by Joel134** [yatharth25/android_dynamic_icon#2]
I wanted to achieve changing app icon dynamically but running into an exception. Can you help?
`I/flutter ( 6534): PlatformException(error, Component class com.example.app.test.MainActivityAlias.icon_1 does not exist in com.example.app.test, null, java.lang.IllegalArgumentException: Component class com.example.app.test.MainActivityAlias.icon_1 does not exist in com.example.app.test
I/flutter ( 6534): 	at android.os.Parcel.createException(Parcel.java:2075)
I/flutter ( 6534): 	at android.os.Parcel.readException(Parcel.java:2039)
I/flutter ( 6534): 	at android.os.Parcel.readException(Parcel.java:1987)
I/flutter ( 6534): 	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:7336)
I/flutter ( 6534): 	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:2554)
I/flutter ( 6534): 	at com.example.android_dynamic_icon.GeneralUtils.changeAppIconDynamically(GeneralUtils.java:17)
I/flutter ( 6534): 	at com.example.android_dynamic_icon.AndroidDynamicIconPlugin.changeIcon(AndroidDynamicIconPlugin.java:49)
I/flutter ( 6534): 	at com.example.android_dynamic_icon.AndroidDynamicIconPlugin.onMethodCall(AndroidDynamicIconPlugin.java:41)
I/flutter ( 6534): 	at io.flutter.plugin.common.MethodChannel$IncomingMet
I/flutter ( 6534):
I/flutter ( 6534): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
I/flutter ( 6534): #1      MethodChannel._invokeMethod
platform_channel.dart:310
I/flutter ( 6534): <asynchronous suspension>
I/flutter ( 6534): #2      MethodChannelAndroidDynamicIcon.changeIcon
android_dynamic_icon_method_channel.dart:24
I/flutter ( 6534): <asynchronous suspension>
I/flutter ( 6534): #3      _ShortcutsListWidgetState.build.<anonymous closure>
shortcuts_list_widget.dart:93
I/flutter ( 6534): <asynchronous suspension>`

**Comment by yatharth25** [comment]
> I wanted to achieve changing app icon dynamically but running into an exception. Can you help? `I/flutter ( 6534): PlatformException(error, Component class com.example.app.test.MainActivityAlias.icon_1 does not exist in com.example.app.test, null, java.lang.IllegalArgumentException: Component class com.example.app.test.MainActivityAlias.icon_1 does not exist in com.example.app.test I/flutter ( 6534): at android.os.Parcel.createException(Parcel.java:2075) I/flutter ( 6534): at android.os.Parcel.readException(Parcel.java:2039) I/flutter ( 6534): at android.os.Parcel.readException(Parcel.java:1987) I/flutter ( 6534): at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:7336) I/flutter ( 6534): at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:2554) I/flutter ( 6534): at com.example.android_dynamic_icon.GeneralUtils.changeAppIconDynamically(GeneralUtils.java:17) I/flutter ( 6534): at com.example.android_dynamic_icon.AndroidDynamicIconPlugin.changeIcon(AndroidDynamicIconPlugin.java:49) I/flutter ( 6534): at com.example.android_dynamic_icon.AndroidDynamicIconPlugin.onMethodCall(AndroidDynamicIconPlugin.java:41) I/flutter ( 6534): at io.flutter.plugin.common.MethodChannel$IncomingMet I/flutter ( 6534): I/flutter ( 6534): #0 StandardMethodCodec.decodeEnvelope message_codecs.dart:652 I/flutter ( 6534): #1 MethodChannel._invokeMethod platform_channel.dart:310 I/flutter ( 6534): <asynchronous suspension> I/flutter ( 6534): #2 MethodChannelAndroidDynamicIcon.changeIcon android_dynamic_icon_method_channel.dart:24 I/flutter ( 6534): <asynchronous suspension> I/flutter ( 6534): #3 _ShortcutsListWidgetState.build.<anonymous closure> shortcuts_list_widget.dart:93 I/flutter ( 6534): <asynchronous suspension>`

Hi @Joel134 can you please show me your AndroidManifest.xml

**Comment by Joel134** [comment]
```
<manifest 
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.example.app">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
    <uses-permission android:name="android.permission.NFC" />
    <uses-permission android:name="android.permission.REQUEST_DELETE_PACKAGES" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    
    <queries>
     <intent>
          <action android:name="android.intent.action.SEND" />
          <data android:mimeType="*/*" />
     </intent>
     <!-- If your app opens https URLs -->
     <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="https" />
     </intent>
     </queries>
     
   <application
        android:label="@string/app_name"
        android:usesCleartextTraffic="true"
        tools:replace="android:usesCleartextTraffic"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/YourLightTheme1"
        android:allowBackup="false">
         <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true"
            android:enabled="true"
            >
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />    
              <meta-data
                android:name="io.flutter.app.icon"
                android:resource="@mipmap/ic_launcher"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
        </activity>

        <activity-alias
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher_new"
        android:name=".icon_1"
        android:enabled="false"
        android:targetActivity=".MainActivity">
        <meta-data
            android:name="io.flutter.embedding.android.NormalTheme"
            android:resource="@style/NormalTheme"
            />
        <meta-data
            android:name="io.flutter.embedding.android.SplashScreenDrawable"
            android:resource="@drawable/launch_background"
            />
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        </activity-alias>

        <!-- Don't delete the meta-data below.
            This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by Joel134** [comment]
Hi, any updated on this?

**Comment by yatharth25** [comment]
> ```
> <manifest 
>   xmlns:android="http://schemas.android.com/apk/res/android"
>   xmlns:tools="http://schemas.android.com/tools"
>   package="com.example.app">
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
>     <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
>     <uses-permission android:name="android.permission.NFC" />
>     <uses-permission android:name="android.permission.REQUEST_DELETE_PACKAGES" />
>     <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
>     <uses-permission android:name="android.permission.CAMERA"/>
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
>     
>     <queries>
>      <intent>
>           <action android:name="android.intent.action.SEND" />
>           <data android:mimeType="*/*" />
>      </intent>
>      
>      <intent>
>           <action android:name="android.intent.action.VIEW" />
>           <data android:scheme="https" />
>      </intent>
>      </queries>
>      
>    <application
>         android:label="@string/app_name"
>         android:usesCleartextTraffic="true"
>         tools:replace="android:usesCleartextTraffic"
>         android:icon="@mipmap/ic_launcher"
>         android:theme="@style/YourLightTheme1"
>         android:allowBackup="false">
>          <activity
>             android:name=".MainActivity"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize"
>             android:exported="true"
>             android:enabled="true"
>             >
>             <meta-data
>               android:name="io.flutter.embedding.android.NormalTheme"
>               android:resource="@style/NormalTheme"
>               />    
>               <meta-data
>                 android:name="io.flutter.app.icon"
>                 android:resource="@mipmap/ic_launcher"/>
> 
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <action android:name="android.intent.action.SEND" />
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>             
>         </activity>
> 
>         <activity-alias
>         android:label="@string/app_name"
>         android:icon="@mipmap/ic_launcher_new"
>         android:name=".icon_1"
>         android:enabled="false"
>         android:targetActivity=".MainActivity">
>         <meta-data
>             android:name="io.flutter.embedding.android.NormalTheme"
>             android:resource="@style/NormalTheme"
>             />
>         <meta-data
>             android:name="io.flutter.embedding.android.SplashScreenDrawable"
>             android:resource="@drawable/launch_background"
>             />
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>         </activity-alias>
> 
>         
>         <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
>     </application>
> </manifest>
> ```

Hi @Joel134 
You need to change android:name in activity alias to
android:name=".MainActivityAliasic_launcher_new"
Please read the documentation, it is mentioned in 4th point clearly
>> All activity alias name must start with MainActivityAlias(for default icon) & MainActivityAlias{iconName}(iconName is name of icon)
